# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('account', '0003_auto_20180602_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='money',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tocken',
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
