# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180602_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='p_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
