# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_subgroup_sublist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='url',
        ),
        migrations.AddField(
            model_name='subgroup',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
