# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20180601_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgroup',
            old_name='user_name',
            new_name='title',
        ),
    ]
