# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_auto_20180601_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
