# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0006_bookmark_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='url',
        ),
    ]
