# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0010_auto_20180601_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
