# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0012_auto_20180602_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Album'),
        ),
    ]
