# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0014_auto_20180602_0230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='sublist',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Album'),
        ),
    ]
