# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0009_remove_album_owner'),
        ('bookmark', '0015_auto_20180602_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photo.Photo'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='star',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
