# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0017_auto_20180603_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='maker',
            field=models.CharField(blank=True, default='미정', max_length=100, null=True),
        ),
    ]
