# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20160131_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='cnt',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세설명'),
        ),
    ]
