# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import photo.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_album_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AddField(
            model_name='photo',
            name='Subscription_ratings',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='cnt',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='purchase_after_sub',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='photo.Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default=0, verbose_name='Photo Description'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=photo.fields.ThumbnailImageField(default=0, upload_to='photo/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
