# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180601_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Subscription_ratings',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='purchase_after_sub',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
