# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20160131_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='owner',
        ),
    ]
