# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20180601_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['origin']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='origin',
        ),
    ]
