# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180601_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['title']},
        ),
    ]
