# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20180601_1847'),
        ('photo', '0005_auto_20180601_1741'),
    ]

    operations = [
    ]
