# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_auto_20180601_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='category',
            field=models.IntegerField(default=4),
        ),
    ]
