# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gudok_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='gudok_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('price', models.CharField(max_length=50)),
                ('Subscription_ratings', models.IntegerField(default=0)),
                ('purchase_after_sub', models.IntegerField(default=0)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gudok.gudok_Album')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
